{
 "title": "BigStats Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "BigStats_Datasource", "query": "graphite" },
   { "name": "BigStatsDevice", "query": "stats.gauges.*" },
   {
    "name": "BigStatsTenant",
    "query": "stats.gauges.$BigStatsDevice.services.*"
   },
   {
    "name": "BigStatsService",
    "query": "stats.gauges.$BigStatsDevice.services.$BigStatsTenant.*"
   },
   {
    "name": "BigStatsPool",
    "query": "stats.gauges.$BigStatsDevice.services.$BigStatsTenant.$BigStatsService.-*"
   }
  ]
 },
 "panels": [
  {
   "title": "BigStats Device - CPU",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(averageSeriesWithWildcards(stats.gauges.$BigStatsDevice.device.cpu*.{cpuUser,cpuSystem}), 4, 5)"
    }
   ]
  },
  {
   "title": "Services - Client Side Connections",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(stats.gauges.$BigStatsDevice.services.$BigStatsTenant.*.*Conns 5, 6)"
    }
   ]
  },
  {
   "title": "BIG-IP Device - Memory",
   "type": "graph",
   "description": "BIG-IP Device RAM Usage",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "target": "stats.gauges.$BigStatsDevice.device.memory.*"
    }
   ]
  },
  {
   "title": "BigStats Service - Pool Connections",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(stats.gauges.$BigStatsDevice.services.$BigStatsTenant.$BigStatsService.$BigStatsPool.*.*Conns, 6, 7, 8)"
    }
   ]
  },
  { "title": "Panel Title", "type": "dashlist", "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 } },
  { "title": "Pool Member  Status Alerts", "type": "alertlist", "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 } }
 ]
}